name       : libgtk-3
version    : 3.24.37
release    : 110
source     :
    - https://download.gnome.org/sources/gtk+/3.24/gtk+-3.24.37.tar.xz : 6745f0b4c053794151fd0f0e2474b077cccff5f83e9dd1bf3d39fe9fe5fb7f57
homepage   : http://www.gnome.org
license    : LGPL-2.0-or-later
summary    :
    - The GTK+ 3 package contains the libraries used for creating graphical user interfaces for applications
    - ^the-widget-factory-3 : GTK3 Application demonstrating the toolkit theming capabilities
    - ^gtk3-demo : Demonstration of major GTK3 features
    - ^gtk3-icon-browser : Sample application to graphically search well known iconnames
component  :
    - desktop.gtk
    - ^the-widget-factory-3 : desktop.gtk
    - ^gtk3-demo : desktop.gtk
    - ^gtk3-icon-browser : desktop.gtk
description:
    - The GTK+ 3 package contains the libraries used for creating graphical user interfaces for applications
    - ^the-widget-factory-3 : GTK3 Application demonstrating the toolkit theming capabilities
    - ^gtk3-demo : Demonstration of major GTK3 features
    - ^gtk3-icon-browser : Sample application to graphically search well known iconnames
patterns   :
    - ^the-widget-factory-3 :
        - /usr/bin/gtk3-widget-factory
        - /usr/share/icons/hicolor/*/apps/gtk3-widget-factory*
        - /usr/share/applications/gtk3-widget-factory.desktop
    - ^gtk3-demo :
        - /usr/bin/gtk3-demo*
        - /usr/share/gtk-3.0/demo
        - /usr/share/glib-2.0/schemas/org.gtk.Demo.gschema.xml
        - /usr/share/icons/hicolor/*/apps/gtk3-demo*
        - /usr/share/applications/gtk3-demo.desktop
    - ^gtk3-icon-browser :
        - /usr/bin/gtk3-icon-browser
        - /usr/share/applications/gtk3-icon-browser.desktop
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(wayland-protocols)
    - pkgconfig32(atk)
    - pkgconfig32(atk-bridge-2.0)
    - pkgconfig32(colord)
    - pkgconfig32(epoxy)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(harfbuzz)
    - pkgconfig32(json-glib-1.0)
    - pkgconfig32(libcap)
    - pkgconfig32(libcrypt)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(mount)
    - pkgconfig32(pango)
    - pkgconfig32(rest-0.7)
    - pkgconfig32(wayland-client)
    - pkgconfig32(xcomposite)
    - pkgconfig32(xcursor)
    - pkgconfig32(xdamage)
    - pkgconfig32(xinerama)
    - pkgconfig32(xi)
    - pkgconfig32(xkbcommon)
    - pkgconfig32(xrandr)
    - pkgconfig32(xshmfence)
    - pkgconfig32(zlib)
    - cups-32bit-devel
rundeps    :
    - gsettings-desktop-schemas
    - hicolor-icon-theme
    - shared-mime-info
emul32     : yes
optimize   :
    - size
setup      : |
    %apply_patches

    # Handle misoptimisation cases
    export CFLAGS="$CFLAGS -fno-strict-aliasing"

    if [[ ! -z $EMUL32BUILD ]]; then
        %meson_configure -Dgtk_doc=true -Dintrospection=false -Dman=true
    else
        %meson_configure -Dgtk_doc=true -Dman=true
    fi
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Compatibility for classic snaps
    if [[ -z "${EMUL32BUILD}" ]]; then
        ln -sv gtk-update-icon-cache $installdir/usr/bin/gtk-update-icon-cache-3.0
    fi

    # Use our desktop file instead
    install -Dm00644 $pkgfiles/gtk3-icon-browser.desktop $installdir/usr/share/applications/gtk3-icon-browser.desktop
