name       : libgtk-3
version    : 3.22.30
release    : 72
source     :
    - https://download.gnome.org/sources/gtk+/3.22/gtk+-3.22.30.tar.xz : a1a4a5c12703d4e1ccda28333b87ff462741dc365131fbc94c218ae81d9a6567
homepage   : http://www.gnome.org
license    :
    - LPL-2.0
summary    :
    - The GTK+ 3 package contains the libraries used for creating graphical user interfaces for applications.
    - ^the-widget-factory-3 : GTK3 Application demonstrating the toolkit theming capabilities
    - ^gtk3-demo : Demonstration of major GTK3 features
    - ^gtk3-icon-browser : Sample application to graphically search well known icon names
component  :
    - desktop.gtk
    - ^the-widget-factory-3 : desktop.gtk
    - ^gtk3-demo : desktop.gtk
    - ^gtk3-icon-browser : desktop.gtk
description: |
    The GTK+ 3 package contains the libraries used for creating graphical user interfaces for applications.
patterns   :
    - ^the-widget-factory-3 :
        - /usr/bin/gtk3-widget-factory
        - /usr/share/icons/hicolor/*/apps/gtk3-widget-factory*
        - /usr/share/applications/gtk3-widget-factory.desktop
    - ^gtk3-demo :
        - /usr/bin/gtk3-demo*
        - /usr/share/gtk-3.0/demo
        - /usr/share/glib-2.0/schemas/org.gtk.Demo.gschema.xml
        - /usr/share/icons/hicolor/*/apps/gtk3-demo*
        - /usr/share/applications/gtk3-demo.desktop
    - ^gtk3-icon-browser :
        - /usr/bin/gtk3-icon-browser
        - /usr/share/applications/gtk3-icon-browser.desktop
builddeps  :
    - pkgconfig(wayland-protocols)
    - pkgconfig32(atk)
    - pkgconfig32(atk-bridge-2.0)
    - pkgconfig32(cairo)
    - pkgconfig32(colord)
    - pkgconfig32(epoxy)
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(harfbuzz)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(gl)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(json-glib-1.0)
    - pkgconfig32(libcap)
    - pkgconfig32(libsoup-2.4)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(mount)
    - pkgconfig32(pango)
    - pkgconfig32(rest-0.7)
    - pkgconfig32(wayland-client)
    - pkgconfig32(xcomposite)
    - pkgconfig32(xcursor)
    - pkgconfig32(xdamage)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
    - pkgconfig32(xinerama)
    - pkgconfig32(xi)
    - pkgconfig32(xkbcommon)
    - pkgconfig32(xrandr)
    - pkgconfig32(xshmfence)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
    - cups-32bit-devel
    - gtk-doc
    - libgcrypt-32bit-devel
emul32     : yes
optimize   :
    - size
setup      : |
    %apply_patches
    install -m 00644 $pkgfiles/server-decoration.xml gdk/wayland/protocol/server-decoration.xml
    # Handle misoptimisation cases
    export CFLAGS="$CFLAGS -fno-strict-aliasing"
    %configure --prefix=/usr \
               --enable-wayland-backend \
               --enable-x11-backend \
               --disable-static
build      : |
    %make
install    : |
    %make_install

    # Compatibility for classic snaps
    if [[ -z "${EMUL32BUILD}" ]]; then
        ln -sv gtk-update-icon-cache $installdir/usr/bin/gtk-update-icon-cache-3.0
    fi
